### ISSUE TITLE
"Who is Running this Study" screen shows placeholder text

### ISSUE THREAD

**Issue by kevinsqi** [ResearchKit/ShareTheJourney#2]
Under "Learn" => "Who is Running this Study", the text shown is "Insert information on who is running this study here":

![ios simulator screen shot may 7 2015 5 45 39 pm](https://cloud.githubusercontent.com/assets/396006/7483648/8ff82cdc-f34e-11e4-806c-f6d35041fb5d.png)

**Comment by jwe-apple** [comment]
Yep, that's correct. To see the real information for this app, download and install it from the app store.

For open source release, it's been redacted so no one inadvertently includes the information from this app in their own.

**Comment by kevinsqi** [comment]
ah, my misunderstanding. thanks!

**Comment by jwe-apple** [comment]
@iqnivek No problem, thanks for asking!
